name: example-utils
minecraft: "1.20"
data_pack:
  load:
    data/test/functions: src
output: dist
require:
  - bolt
  - bolt_expressions
  - beet_plugins.utils
pipeline:
  - mecha
meta:
  generate_namespace: "test"